In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [16]:
# initalise concentration field with linear field 
N = 10
y = np.linspace(N,1,N)
max_growth = 100
eta = 1

c_current = np.zeros((N,N))
c_current[:,] = y.reshape(N, 1)
# start with bottom point

c_current[4,0]= 0 
# calculate SOR 


c_current = np.zeros((N,N))
c_current[:,] = y.reshape(N, 1)

grid  = np.zeros((N,N))
grid[-1,4]= 1
print(grid)


for i in range (1,max_growth):
    candidates = []
    
        #for _ in range(i)   range over how many points are already sink if we are at iteration 1 then there is one point to check its 1
        # if c
    


# 


    
def SOR_object(c_last, w, epsilon,N):
    c_current = c_last.copy()
    c_next = np.zeros((N, N))

    c_current[-1, :] = 0
    c_current[0, :] = 1  

    iteration = 0
    grid = object(N,object_size,number_objects)
    while iteration < max_iter:
        c_next = c_current.copy()  

        for i in range(1,N-1):
            for j in range(1,N-1):
                if c_last[i, j]== 0:
                    c_next[i,j] = 0
                else:
                    c_next[i,j] = (w/4)*(c_current[(i+1)%N,j] + c_next[(i-1)%N,j] +c_current[i,j+1] +c_next[i,j-1]) + (1-w)*c_current[i,j]

        c_next[-1, :] = 0
        c_next[0, :] = 1
        c_next[:, 0] = c_next[:, 1]
        c_next[:, -1] = c_next[:, -2]

        delta = np.max(np.abs(c_next - c_current))
        if delta < epsilon:
            return c_current, iteration

        c_current[:, :] = c_next[:, :]
        iteration += 1
    return c_current, iteration

# then locating growth candidates aroundthe cluster, and 

#assigning a growth probability pg for each growth candidate, as a function of the concentration of diffusing nutrients at that growth location. Next,
#a single growth candidate is added to the cluster with probability pg .
#After thisgrowth step, the diffusion equation is again solved, and the process is iterated for
#a large number of growth steps.

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
